version: '2.4'
services:
  camwatchdog:
    image: drjp81/camwatchdog:latest
    container_name: watchdog
    restart: unless-stopped
    volumes:
      - /media/POOL4/rancherdata/watchdog/config/:/app/config
      - /etc/timezone:/etc/timezone:ro
    command: ["/usr/bin/pwsh","-file", "/app/script/watch.ps1"]
    environment:
      - TZ=America/Toronto
    healthcheck:
     test: ["CMD", "/usr/bin/pwsh", "-file", "/app/script/health.ps1"]
     interval: 60s
     timeout: 15s
     retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: 50m